"""initial station schema

Revision ID: 9ef5d63e2281
Revises: 
Create Date: 2026-10-01 11:55:59.605866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef5d63e2281'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('allocation_id', sa.String(length=128), nullable=False),
    sa.Column('station_id', sa.String(length=128), nullable=False),
    sa.Column('jig_id', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('document_digest', sa.String(length=128), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('STOCK_RF_TEST', 'PRICOL_PRODUCTION')", name='ck_allocations_purpose'),
    sa.CheckConstraint('schema_version >= 1', name='ck_allocations_schema_version'),
    sa.PrimaryKeyConstraint('allocation_id'),
    sa.UniqueConstraint('document_digest')
    )
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocations_jig_id'), ['jig_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocations_station_id'), ['station_id'], unique=False)

    op.create_table('audit_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('station_id', sa.String(length=128), nullable=False),
    sa.Column('record_type', sa.String(length=128), nullable=False),
    sa.Column('record_id', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id')
    )
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.create_index('ix_audit_records_record', ['record_type', 'record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_user_id'), ['user_id'], unique=False)

    op.create_table('batches',
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=128), nullable=False),
    sa.Column('jig_id', sa.String(length=128), nullable=False),
    sa.Column('slot_count', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('slot_count IN (4, 8)', name='ck_batches_slot_count'),
    sa.PrimaryKeyConstraint('batch_id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_jig_id'), ['jig_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_state'), ['state'], unique=False)
        batch_op.create_index('ix_batches_station_created', ['station_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_station_id'), ['station_id'], unique=False)

    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_transaction_id', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("\n            status IN (\n                'PENDING',\n                'RETRY',\n                'UPLOADED'\n            )\n            ", name='ck_outbox_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_outbox_attempt_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_transaction_id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index('ix_outbox_pending', ['status', 'next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_status'), ['status'], unique=False)

    op.create_table('allocated_macs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('allocation_id', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=12), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('module_qr', sa.String(length=256), nullable=True),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('programming_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            status IN (\n                'AVAILABLE',\n                'RESERVED',\n                'PROGRAMMING',\n                'ISSUED',\n                'CONFIRMED',\n                'HOLD'\n                )\n            ", name='ck_allocated_macs_status'),
    sa.CheckConstraint("purpose IN ('STOCK_RF_TEST', 'PRICOL_PRODUCTION')", name='ck_allocated_macs_purpose'),
    sa.CheckConstraint('slot_number IS NULL OR slot_number > 0', name='ck_allocated_macs_slot_positive'),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.allocation_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', name='uq_allocated_macs_address'),
    sa.UniqueConstraint('batch_id', 'slot_number', 'purpose', name='uq_allocated_macs_batch_slot_purpose')
    )
    with op.batch_alter_table('allocated_macs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocated_macs_allocation_id'), ['allocation_id'], unique=False)
        batch_op.create_index('ix_allocated_macs_available', ['purpose', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocated_macs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocated_macs_module_qr'), ['module_qr'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocated_macs_status'), ['status'], unique=False)

    op.create_table('batch_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('port_identity', sa.String(length=256), nullable=True),
    sa.Column('device_state', sa.String(length=64), nullable=False),
    sa.Column('module_qr', sa.String(length=256), nullable=True),
    sa.Column('pricol_app_passed', sa.Boolean(), nullable=True),
    sa.Column('pricol_dfu_passed', sa.Boolean(), nullable=True),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.CheckConstraint('slot_number > 0', name='ck_batch_slots_slot_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'port_identity', name='uq_batch_slots_batch_port'),
    sa.UniqueConstraint('batch_id', 'slot_number', name='uq_batch_slots_batch_slot'),
    sa.UniqueConstraint('module_qr')
    )
    with op.batch_alter_table('batch_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_slots_batch_id'), ['batch_id'], unique=False)

    op.create_table('manufacturing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('slot_number IS NULL OR slot_number > 0', name='ck_manufacturing_events_slot_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('manufacturing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manufacturing_events_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manufacturing_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manufacturing_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_manufacturing_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('programming_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('requested_mac', sa.String(length=12), nullable=False),
    sa.Column('firmware_version', sa.String(length=128), nullable=True),
    sa.Column('tool_version', sa.String(length=128), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.Column('uncertain', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.CheckConstraint("purpose IN ('STOCK_RF_TEST', 'PRICOL_PRODUCTION')", name='ck_programming_events_purpose'),
    sa.CheckConstraint('slot_number > 0', name='ck_programming_events_slot_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programming_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programming_events_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_programming_events_batch_slot', ['batch_id', 'slot_number'], unique=False)

    op.create_table('verification_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('verification_type', sa.String(length=32), nullable=False),
    sa.Column('expected_mac', sa.String(length=12), nullable=False),
    sa.Column('reported_mac', sa.String(length=12), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.CheckConstraint("\n            verification_type IN (\n                'STOCK_RF',\n                'PRICOL_READBACK'\n            )\n            ", name='ck_verification_events_type'),
    sa.CheckConstraint('slot_number > 0', name='ck_verification_events_slot_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_events_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_verification_events_batch_slot', ['batch_id', 'slot_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_events', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_events_batch_slot')
        batch_op.drop_index(batch_op.f('ix_verification_events_batch_id'))

    op.drop_table('verification_events')
    with op.batch_alter_table('programming_events', schema=None) as batch_op:
        batch_op.drop_index('ix_programming_events_batch_slot')
        batch_op.drop_index(batch_op.f('ix_programming_events_batch_id'))

    op.drop_table('programming_events')
    with op.batch_alter_table('manufacturing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manufacturing_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_manufacturing_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_manufacturing_events_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_manufacturing_events_batch_id'))

    op.drop_table('manufacturing_events')
    with op.batch_alter_table('batch_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_slots_batch_id'))

    op.drop_table('batch_slots')
    with op.batch_alter_table('allocated_macs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocated_macs_status'))
        batch_op.drop_index(batch_op.f('ix_allocated_macs_module_qr'))
        batch_op.drop_index(batch_op.f('ix_allocated_macs_batch_id'))
        batch_op.drop_index('ix_allocated_macs_available')
        batch_op.drop_index(batch_op.f('ix_allocated_macs_allocation_id'))

    op.drop_table('allocated_macs')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_status'))
        batch_op.drop_index('ix_outbox_pending')
        batch_op.drop_index(batch_op.f('ix_outbox_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_aggregate_id'))

    op.drop_table('outbox')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_station_id'))
        batch_op.drop_index('ix_batches_station_created')
        batch_op.drop_index(batch_op.f('ix_batches_state'))
        batch_op.drop_index(batch_op.f('ix_batches_jig_id'))

    op.drop_table('batches')
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_records_station_id'))
        batch_op.drop_index('ix_audit_records_record')

    op.drop_table('audit_records')
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocations_station_id'))
        batch_op.drop_index(batch_op.f('ix_allocations_jig_id'))

    op.drop_table('allocations')
    # ### end Alembic commands ###
