"""Append-only persistence repository for manufacturing history.

Manufacturing events are historical evidence.

Repository rules:

* events may be appended;
* events may be queried;
* historical events are never updated;
* historical events are never deleted;
* a retry creates another event rather than modifying the first event.

Transaction ownership deliberately remains outside this repository.
The repository flushes changes but does not commit them. Lesson 6D will
introduce the Unit of Work that owns commit and rollback.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from stationapp.data.errors import DuplicateManufacturingEvent
from stationapp.data.models import ManufacturingEventModel
from stationapp.domain.events import EventType, ManufacturingEvent


_CONTEXT_KEY = "context"
_DATA_KEY = "data"

def _as_aware_utc(value: datetime) -> datetime:
    """Return a timezone-aware UTC datetime.

    SQLite stores Python datetimes without preserving timezone metadata.
    The station application writes all manufacturing timestamps in UTC,
    so a naive timestamp read back from SQLite is interpreted as UTC.
    """

    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)

    return value.astimezone(timezone.utc)



class ManufacturingEventRepository:
    """Append-only repository for immutable manufacturing history.

    Important:
        This repository intentionally contains no update() or delete()
        operation.

    It works with an existing SQLAlchemy Session so a later Unit of Work
    can combine event creation with other changes in one database
    transaction.
    """

    def __init__(self, session: Session) -> None:
        self._session = session

    def append(self, event: ManufacturingEvent, *, correlation_id: str | None = None) -> ManufacturingEvent:
        """Append one manufacturing event.

        The event is inserted as a completely new historical record.

        Args:
            event:
                Immutable domain manufacturing event.

            correlation_id:
                Optional operation identifier used to group several events
                generated by the same higher-level station operation.

        Returns:
            The original domain event.

        Raises:
            DuplicateManufacturingEvent:
                If event.event_id already exists.

        Notes:
            This method performs flush(), not commit().

            Transaction ownership belongs to the caller and later to the
            Lesson 6D Unit of Work.
        """

        stored_payload = self._serialise_payload(event)

        model = ManufacturingEventModel(
            event_id=event.event_id,
            batch_id=event.batch_id,
            slot_number=event.slot_number,
            event_type=event.event_type.value,
            correlation_id=correlation_id,
            payload=stored_payload,
            occurred_at=event.occurred_at,
        )

        self._session.add(model)

        try:
            self._session.flush()

        except IntegrityError as exc:
            # flush failure leaves the current transaction unusable until
            # rollback. The Unit of Work / caller owns the rollback itself.
            raise DuplicateManufacturingEvent(
                f"Manufacturing event {event.event_id} already exists"
            ) from exc

        return event

    def get(self, event_id: str) -> ManufacturingEvent | None:
        """Return one manufacturing event by its globally unique ID."""

        identifier = event_id.strip()

        if not identifier:
            raise ValueError("event_id cannot be empty")

        model = self._session.scalar(
            select(ManufacturingEventModel).where(
                ManufacturingEventModel.event_id == identifier
            )
        )

        if model is None:
            return None

        return self._to_domain(model)

    def list_for_batch(self, batch_id: str) -> tuple[ManufacturingEvent, ...]:
        """Return complete manufacturing history for one batch.

        Ordering is deterministic:

            occurred_at
            database id

        The database id provides a stable tie-breaker if two events have
        exactly the same timestamp.
        """

        identifier = batch_id.strip()

        if not identifier:
            raise ValueError("batch_id cannot be empty")

        rows = self._session.scalars(
            select(ManufacturingEventModel)
            .where(
                ManufacturingEventModel.batch_id == identifier
            )
            .order_by(
                ManufacturingEventModel.occurred_at,
                ManufacturingEventModel.id,
            )
        ).all()

        return tuple(
            self._to_domain(row)
            for row in rows
        )

    def count_for_batch(
        self,
        batch_id: str,
    ) -> int:
        """Return the number of historical events stored for a batch."""

        return len(
            self.list_for_batch(batch_id)
        )

    @staticmethod
    def _serialise_payload(event: ManufacturingEvent) -> dict[str, Any]:
        """Convert the domain event into the JSON payload stored in SQLite.

        station_id, jig_id and module_qr are domain identity fields but the
        Lesson 5 manufacturing_events table does not have dedicated columns
        for them.

        They therefore live in the event context envelope.
        """

        return {
            _CONTEXT_KEY: {
                "station_id": event.station_id,
                "jig_id": event.jig_id,
                "module_qr": event.module_qr,
            },
            _DATA_KEY: deepcopy(event.payload),
        }

    @staticmethod
    def _to_domain(
        model: ManufacturingEventModel,
    ) -> ManufacturingEvent:
        """Reconstruct the immutable domain event from persistence."""

        stored_payload = model.payload or {}

        context = stored_payload.get(
            _CONTEXT_KEY,
            {},
        )

        payload = stored_payload.get(
            _DATA_KEY,
            {},
        )

        station_id = context.get("station_id")
        jig_id = context.get("jig_id")
        module_qr = context.get("module_qr")

        if not station_id:
            raise ValueError(
                f"Manufacturing event {model.event_id} "
                "does not contain station_id"
            )

        if not jig_id:
            raise ValueError(
                f"Manufacturing event {model.event_id} "
                "does not contain jig_id"
            )

        return ManufacturingEvent(
            event_id=model.event_id,
            event_type=EventType(model.event_type),
            batch_id=model.batch_id or "",
            station_id=station_id,
            jig_id=jig_id,
            slot_number=model.slot_number,
            module_qr=module_qr,
            payload=deepcopy(payload),
            occurred_at=_as_aware_utc(model.occurred_at),
        )


    